language: node_js
node_js:
- lts/*
branches:
  only:
  - master
  - test
env:
  secure: Cra3l5PiQ4g6BhpCxFzS3jmqAYt7rVXtzJEcBFtJ/axrsDYNQ7wPEA9vQblUGLsGRMXpGHWDOff5Oeu9YcUDk37zvD6QAJDs2jFcg3F6HtgLW9p6YrYE0D/47Uoi7ewk/fufFBBouHtWcLzf7BYWarQivAyVNt48JkIOmKrO9HeeiwuKmgTgNFZfWVcY/71VVGICtugNZaMAi1f+0VAhBUPcPHR7zSaI/NjdXIPRXhV1Yt/sMfhZ/ZoQLTdx4C61oDFHn99528s8efucsw1QmSrNT1GrzIHC3BT4nj+h8Q2FOuGztMe4GCQfayhy9lNkuvk6aI52uTMO+KmUaF06doStDScOpkMHjTEsp4gDQWkqzZ25YK5ZuGEZFPOHkRaB6DRQvf+lM/XfEoCsn4g16wDXsULZ4HSgimuQ/ZyVGisCmQ5V2JyDPqhI67obDYcVDHsxMugbVXJoc6DmsyzcfqnJsHBLsG2AS6+xRzdZYplqqbo5vr7UrwenAX9Qh1YwuBhDg6DtIFhSxYD1F9GaZjqtrbRB499VkcNPKxmYPouB5bCpQ7lAV7SMbjapw+oaPFOKdAlgNYsDFQaIgIbD26berSjkuAP/2Z0ht1gKICL0aGuTj4sE9jagOoK6uygj9jZrHZPLWxPkVkZCRqDKOID6Yhn5uYY4FAgnCdHkBXU=
