language: node_js
node_js:
- node
branches:
  only:
  - master
  - test

env:
  - MONGODB_URI="kXKis42EN9wFO2i3O0R2A4MHursCMuf7n2XvX515Gz74rm2oDZ2XfdHwXkSoJ+6DgdRfY+wUSzgiVwxt//6d7lQIHe90ZnyjKyxnLWCBXf/zD1g5O7/EUrYnLEp+t9VDzjz0MReHYObtmEiYgi9TflYKrK4HfQTcA0A0wfa/4e4y76bFE1FTlV1ViO42KsfnDOwqnwsEet+taYhnnd+SFp1teaFA3BwY3MukgQCt2LSx7wS5KxjRiqOpMXZVpnK++6byLop/FPqRwKuSPVl45BGmEF3mZE1bYGYK7QGdZW8L4nSyJi9nRzhk9cwgUfFySxhPUuHTNMrp2Z9Es7W4yDN6fJqjM9TcDL9Nm3sLFo1mNoBR9I7m023nQ62B6WVSpfXc+8YQKeM1N4jZBZJ/hZr11l0ILqOIm8QNAbFp3Hwn1zmPodNCGIP7V/n38tRUGvuV/KwE9hgUTUnzjkIWw4Cs4aux06KIojDhjXjnr7Xv6NVT1slI6/3YL16quT+J2us0f1zPnHgS+pkmgHpEv0vFMTDgRNS5YoMmXDVR5YXku0PGq5MV8Ee6UE5BXN61yv2i3oxHoyDv9a5cdnkiTsxag7cgAKHz8lnL2UQQCGp/avztNemifFjgyNqvkrjDnTaAX2G9ZuGy1Bwck/5BOcyI2YyD/TFn5KKy+1lsx2k=" PORT=3000
