language: node_js
node_js:
- lts/*
branches:
  only:
  - master
env:
  secure: mQYvJQaiVb0fx68hdPNahJzGRJvaL6X/0SB/35TBL1ZqzjoMmIMzwTR6E7knya+01Px9Ub5x5wiDkWOaAXdrprR0xEMP4Xf7F+RmiU1OX/q1GqBYoHoOGI62Zmo/lwSKKj4XdKBFCHWQjtP/4x7eZiJ99/1qfEmwIa+v/eDtf2BqyRm1hXihHdix+Nq4CJno103+xL2pj03gkX4U/Hlk6GhvMFvFvocr6mK+ct203191pGWE2UY94UjVY7RiprizPxjZaXdPfaM4cIQCduQCWD74+aHExN/H2iwZeDY34njmST1QbJQRN4InbUZJdijrj4aj3rnNWiUqpaDBA/QIqFHksqwYzIhrsJFNZmA/bhpxzSJU6Hj84RhKVsgcFtSx5IOUA4gtF9Mkow2n1PAClTgZfauw64AMamkpQkeTdmv7BngE5w/GdpPfGi9I3UWKjMrjDwWqKZjjfx/5AlzmLMWjhXFkmUjvt7insTEgLW71s6GJWZsTHTO/BH9NmSBRJmt9rnlDqxmRkuXJNhNj7hY1FzlqpMEIxbxC/NSEvHRc8hnr9qwMrGrP7Vun51nhqM3H1ekRNGjaw3g0LnIUAZrSMqXkpSf2ab+ieIEALP3wSNzrQb9pnvRWWAxFxUENs50/exYrzUus73WtmeelpsZxxGeEBmMGPt5EtjQAgoQ=
