---
version: "3"

volumes:
  database:

networks:
  snapy:
  nginx-proxy-manager_default:
    external: true
  mq:
    external: true

services:
  app:
    image: ghcr.io/spaceflightnewsapi/spaceflightnewsapi:development
    command: >
      python manage.py collectstatic --no-input &&
      gunicorn snapy.wsgi:application --bind 0.0.0.0:8000
    networks:
      - snapy
      - nginx-proxy-manager_default
    volumes:
      - /srv/static/spaceflightnewsapi:/code/static
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - URL_SCHEME=${URL_SCHEME}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - LL_URL=${LL_URL}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
    depends_on:
      - database

  database:
    image: postgres:15-alpine
    networks:
      - snapy
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  beat:
    image: ghcr.io/spaceflightnewsapi/spaceflightnewsapi:development
    command: celery -A snapy beat -l INFO
    networks:
      - mq
      - snapy
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
    depends_on:
      - app
      - database


  worker:
    image: ghcr.io/spaceflightnewsapi/spaceflightnewsapi:development
    command: celery -A snapy worker -l INFO
    networks:
      - mq
      - snapy
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - LL_URL=${LL_URL}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
    depends_on:
      - app
      - database
