---
version: "3"

volumes:
  database:

networks:
  snapy:
  nginx-proxy-manager_default:
    external: true
  mq:
    external: true

services:
  app:
    image: ghcr.io/spaceflightnewsapi/spaceflightnewsapi:development
    command:
      - /bin/sh
      - -c
      - |
        python manage.py collectstatic --no-input &&
        python manage.py migrate --no-input &&
        python manage.py createdefaulttasks &&
        gunicorn snapy.wsgi:application --bind 0.0.0.0:8000
    networks:
      - snapy
      - nginx-proxy-manager_default
    volumes:
      - /srv/static/spaceflightnewsapi:/code/static
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - CSRF_TRUSTED_ORIGIN=${CSRF_TRUSTED_ORIGIN}
      - LL_URL=${LL_URL}
      - LL_TOKEN=${LL_TOKEN}
      - USE_MINIO=${USE_MINIO}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
    depends_on:
      - database

  database:
    image: postgres:15-alpine
    networks:
      - snapy
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  beat:
    image: ghcr.io/spaceflightnewsapi/spaceflightnewsapi:development
    command: celery -A snapy beat -l INFO
    networks:
      - mq
      - snapy
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CSRF_TRUSTED_ORIGIN=${CSRF_TRUSTED_ORIGIN}
    depends_on:
      - app
      - database


  worker:
    image: ghcr.io/spaceflightnewsapi/spaceflightnewsapi:development
    command: celery -A snapy worker -l INFO
    networks:
      - mq
      - snapy
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - LL_URL=${LL_URL}
      - LL_TOKEN=${LL_TOKEN}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CSRF_TRUSTED_ORIGIN=${CSRF_TRUSTED_ORIGIN}
    depends_on:
      - app
      - database
