
name: Update README

on:
  workflow_dispatch:
  schedule:
    - cron: "*/60 * * * *"   # every 60 mins

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Generate access token
        id: get_installation_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.SNAPI_APP_ID }}
          private_key: ${{ secrets.SNAPI_APP_PRIVATE_KEY }}
      - name: 🍽️ Get working copy
        uses: actions/checkout@master
        with:
          fetch-depth: 1                                                                 
      - name: 🐍 Set up Python 3.8                               
        uses: actions/setup-python@v2                               
        with:                                 
          python-version: '3.8'                                                   
      - name: 💿 Install Jinja2 & requests                           
        run: pip install Jinja2 requests
      - name: 🍳 Update README
        run: |
          cd ${GITHUB_WORKSPACE}/.github/profile/src/
          python update.py
      - name: 🚀 Deploy
        env:
          GH_TOKEN: ${{ steps.get_installation_token.outputs.token }}
        run: |
          gh auth status
          gh auth setup-git
          git add .
          git commit -am "feat(auto generate): Updated README"
          git push --all -f https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
