
name: Update README

on:
  workflow_dispatch:
  schedule:
    - cron: "*/60 * * * *"   # every 60 mins

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Generate JWT and token
        id: generate-github-app-tokens
        uses: jamestrousdale/github-app-jwt-token@0.1.4
        with:
          app-id: ${{ secrets.SNAPI_APP_ID }}
          private-key: ${{ secrets.SNAPI_APP_PRIVATE_KEY }}
      - name: 🍽️ Get working copy
        uses: actions/checkout@master
        with:
          fetch-depth: 1                                                                 
      - name: 🐍 Set up Python 3.8                               
        uses: actions/setup-python@v2                               
        with:                                 
          python-version: '3.8'                                                   
      - name: 💿 Install Jinja2 & requests                           
        run: pip install Jinja2 requests
      - name: 🍳 Update README
        run: |
          cd ${GITHUB_WORKSPACE}/.github/profile/src/
          python update.py
      - name: 🚀 Deploy
        env:
          GITHUB_JWT: ${{ steps.generate-github-app-tokens.outputs.jwt }}
          APP_TOKEN: ${{ steps.generate-github-app-tokens.outputs.access-token }}
        run: |
          gh auth login --with-token ${APP_TOKEN}
          gh auth setup-git
          git add .
          git commit -am "feat(auto generate): Updated README"
          git push --all -f https://x-access-token:${APP_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
