
name: Update README

on:
  workflow_dispatch:
  schedule:
    - cron: "*/60 * * * *"   # every 60 mins

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Generate access token
        id: get_installation_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.SNAPI_APP_ID }}
          private_key: ${{ secrets.SNAPI_APP_PRIVATE_KEY }}
      - name: 🍽️ Get working copy
        uses: actions/checkout@main
        with:
          fetch-depth: 1
      - name: Create branch
        env:
          GH_TOKEN: ${{ secrets.SNAPI_BOT_TOKEN }}
        run: |
          gh auth setup-git
          gh auth status
          git config user.name "snapi-bot"
          git config user.email "134217814+snapi-bot@users.noreply.github.com"
          git checkout -b readme-update
      - name: 🐍 Set up Python 3.8                               
        uses: actions/setup-python@v2                               
        with:                                 
          python-version: '3.8'                                                   
      - name: 💿 Install Jinja2 & requests                           
        run: pip install Jinja2 requests
      - name: 🍳 Update README
        run: |
          cd ${GITHUB_WORKSPACE}/.github/profile/src/
          python update.py
      - name: 🚀 Deploy
        env:
          GH_TOKEN: ${{ secrets.SNAPI_BOT_TOKEN }}
        run: |
          git add .
          git commit -u -am "feat(auto generate): Updated content"
          git push -f -u origin readme-update
          git checkout main
          git merge -m "Update README" readme-update
          git push origin :readme-update
