
name: Update README

on:
  workflow_dispatch:
  schedule:
    - cron: "*/60 * * * *"   # every 60 mins

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Obtain GitHub App Installation Access Token
        id: get_token
        uses: machine-learning-apps/actions-app-token@master
        with:
          APP_PEM: ${{ secrets.SNAPI_APP_PRIVATE_KEY_CLEAN }}
          APP_ID: ${{ secrets.SNAPI_APP_ID }}
      - name: 🍽️ Get working copy
        uses: actions/checkout@master
        with:
          fetch-depth: 1                                                                 
      - name: 🐍 Set up Python 3.8                               
        uses: actions/setup-python@v2                               
        with:                                 
          python-version: '3.8'                                                   
      - name: 💿 Install Jinja2 & requests                           
        run: pip install Jinja2 requests
      - name: 🍳 Update README
        run: |
          cd ${GITHUB_WORKSPACE}/.github/profile/src/
          python update.py
      - name: 🚀 Deploy
        env:
          TOKEN: ${{ steps.get_token.outputs.app_token }}
        run: |
          git config user.name "SNAPI Github Actions"
          git config user.email "SNAPI-Github-Actions@users.noreply.github.com"
          git add .
          git commit -am "feat(auto generate): Updated README"
          git push --all -f https://x-access-token:${TOKEN}@github.com/${GITHUB_REPOSITORY}.git
